-- Run this in Supabase SQL Editor.
-- It creates app tables needed for DB persistence + admin metrics.

create table if not exists public.trip_states (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.app_visits (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  user_email text not null,
  visited_at timestamptz not null default now()
);

create table if not exists public.user_presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  user_email text not null,
  user_name text not null,
  last_seen timestamptz not null default now()
);

alter table public.trip_states enable row level security;
alter table public.app_visits enable row level security;
alter table public.user_presence enable row level security;

-- trip_states policies
create policy if not exists "trip_states_select_own"
  on public.trip_states
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy if not exists "trip_states_upsert_own"
  on public.trip_states
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy if not exists "trip_states_update_own"
  on public.trip_states
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- app_visits policies
create policy if not exists "app_visits_insert_authenticated"
  on public.app_visits
  for insert
  to authenticated
  with check (true);

create policy if not exists "app_visits_select_authenticated"
  on public.app_visits
  for select
  to authenticated
  using (true);

-- user_presence policies
create policy if not exists "user_presence_select_authenticated"
  on public.user_presence
  for select
  to authenticated
  using (true);

create policy if not exists "user_presence_upsert_own"
  on public.user_presence
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy if not exists "user_presence_update_own"
  on public.user_presence
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists idx_app_visits_visited_at on public.app_visits (visited_at desc);
create index if not exists idx_user_presence_last_seen on public.user_presence (last_seen desc);
