-- Run this in Supabase SQL Editor.
-- It creates app tables needed for DB persistence + admin metrics.

create table if not exists public.trip_states (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.trip_expenses (
  trip_id text not null,
  expense_id text not null,
  payload jsonb not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (trip_id, expense_id)
);

create table if not exists public.trip_expense_events (
  id bigint generated by default as identity primary key,
  trip_id text not null,
  expense_id text not null,
  event_type text not null check (event_type in ('created', 'updated', 'deleted')),
  payload jsonb,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.app_visits (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  user_email text not null,
  visited_at timestamptz not null default now()
);

create table if not exists public.user_presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  user_email text not null,
  user_name text not null,
  last_seen timestamptz not null default now()
);

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'user')),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_announcements (
  id int primary key,
  message text not null default '',
  enabled boolean not null default false,
  updated_at timestamptz not null default now()
);

insert into public.admin_announcements (id, message, enabled)
values (1, '', false)
on conflict (id) do nothing;

create or replace function public.is_admin(target_user uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles
    where user_id = target_user
      and role = 'admin'
  );
$$;

grant execute on function public.is_admin(uuid) to authenticated;

create or replace function public.can_access_trip(target_trip_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.trip_states ts,
         jsonb_array_elements(coalesce(ts.state_json->'trips', '[]'::jsonb)) trip_elem
    where ts.user_id = auth.uid()
      and trip_elem->>'id' = target_trip_id
  );
$$;

grant execute on function public.can_access_trip(text) to authenticated;

alter table public.trip_states enable row level security;
alter table public.trip_expenses enable row level security;
alter table public.trip_expense_events enable row level security;
alter table public.app_visits enable row level security;
alter table public.user_presence enable row level security;
alter table public.user_roles enable row level security;
alter table public.admin_announcements enable row level security;

-- trip_states policies
drop policy if exists "trip_states_select_own" on public.trip_states;
create policy "trip_states_select_own"
  on public.trip_states
  for select
  to authenticated
  using (auth.uid() = user_id or public.is_admin(auth.uid()));

drop policy if exists "trip_states_upsert_own" on public.trip_states;
create policy "trip_states_upsert_own"
  on public.trip_states
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "trip_states_update_own" on public.trip_states;
create policy "trip_states_update_own"
  on public.trip_states
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- trip_expenses policies
drop policy if exists "trip_expenses_select_member" on public.trip_expenses;
create policy "trip_expenses_select_member"
  on public.trip_expenses
  for select
  to authenticated
  using (public.can_access_trip(trip_id));

drop policy if exists "trip_expenses_insert_member" on public.trip_expenses;
create policy "trip_expenses_insert_member"
  on public.trip_expenses
  for insert
  to authenticated
  with check (public.can_access_trip(trip_id));

drop policy if exists "trip_expenses_update_member" on public.trip_expenses;
create policy "trip_expenses_update_member"
  on public.trip_expenses
  for update
  to authenticated
  using (public.can_access_trip(trip_id))
  with check (public.can_access_trip(trip_id));

drop policy if exists "trip_expenses_delete_member" on public.trip_expenses;
create policy "trip_expenses_delete_member"
  on public.trip_expenses
  for delete
  to authenticated
  using (public.can_access_trip(trip_id));

-- trip_expense_events policies
drop policy if exists "trip_expense_events_select_member" on public.trip_expense_events;
create policy "trip_expense_events_select_member"
  on public.trip_expense_events
  for select
  to authenticated
  using (public.can_access_trip(trip_id));

drop policy if exists "trip_expense_events_insert_member" on public.trip_expense_events;
create policy "trip_expense_events_insert_member"
  on public.trip_expense_events
  for insert
  to authenticated
  with check (public.can_access_trip(trip_id));

-- app_visits policies
drop policy if exists "app_visits_insert_authenticated" on public.app_visits;
create policy "app_visits_insert_authenticated"
  on public.app_visits
  for insert
  to authenticated
  with check (true);

drop policy if exists "app_visits_select_authenticated" on public.app_visits;
create policy "app_visits_select_authenticated"
  on public.app_visits
  for select
  to authenticated
  using (public.is_admin(auth.uid()));

-- user_presence policies
drop policy if exists "user_presence_select_authenticated" on public.user_presence;
create policy "user_presence_select_authenticated"
  on public.user_presence
  for select
  to authenticated
  using (public.is_admin(auth.uid()) or auth.uid() = user_id);

drop policy if exists "user_presence_upsert_own" on public.user_presence;
create policy "user_presence_upsert_own"
  on public.user_presence
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "user_presence_update_own" on public.user_presence;
create policy "user_presence_update_own"
  on public.user_presence
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- user_roles policies
drop policy if exists "user_roles_select_own_or_admin" on public.user_roles;
create policy "user_roles_select_own_or_admin"
  on public.user_roles
  for select
  to authenticated
  using (auth.uid() = user_id or public.is_admin(auth.uid()));

drop policy if exists "user_roles_insert_admin" on public.user_roles;
create policy "user_roles_insert_admin"
  on public.user_roles
  for insert
  to authenticated
  with check (public.is_admin(auth.uid()));

drop policy if exists "user_roles_update_admin" on public.user_roles;
create policy "user_roles_update_admin"
  on public.user_roles
  for update
  to authenticated
  using (public.is_admin(auth.uid()))
  with check (public.is_admin(auth.uid()));

drop policy if exists "user_roles_delete_admin" on public.user_roles;
create policy "user_roles_delete_admin"
  on public.user_roles
  for delete
  to authenticated
  using (public.is_admin(auth.uid()));

-- admin_announcements policies
drop policy if exists "admin_announcements_select_authenticated" on public.admin_announcements;
create policy "admin_announcements_select_authenticated"
  on public.admin_announcements
  for select
  to authenticated
  using (true);

drop policy if exists "admin_announcements_insert_admin" on public.admin_announcements;
create policy "admin_announcements_insert_admin"
  on public.admin_announcements
  for insert
  to authenticated
  with check (public.is_admin(auth.uid()));

drop policy if exists "admin_announcements_update_admin" on public.admin_announcements;
create policy "admin_announcements_update_admin"
  on public.admin_announcements
  for update
  to authenticated
  using (public.is_admin(auth.uid()))
  with check (public.is_admin(auth.uid()));

create index if not exists idx_app_visits_visited_at on public.app_visits (visited_at desc);
create index if not exists idx_user_presence_last_seen on public.user_presence (last_seen desc);
create index if not exists idx_user_roles_role on public.user_roles (role);
create index if not exists idx_trip_expenses_trip_id on public.trip_expenses (trip_id);
create index if not exists idx_trip_expenses_trip_updated_at on public.trip_expenses (trip_id, updated_at desc);
create index if not exists idx_trip_expense_events_trip_expense_created_at on public.trip_expense_events (trip_id, expense_id, created_at desc);
